### ISSUE TITLE
Device authenication

### ISSUE THREAD

**Issue by mmihir82** [StackStorm-Exchange/stackstorm-napalm#43]
Hello
How to load 500+ device credential to use the same username pass, /opt/stackstorm/configs/napalm.yaml. 
Is there global setting which st2/napalm is able to fetch. 
Thank you

**Comment by nmaludy** [comment]
Can you use a `credentials_group` since they're all the same, instead of storing them individually for every device?

https://github.com/StackStorm-Exchange/stackstorm-napalm/blob/master/napalm.yaml.example#L5

https://github.com/StackStorm-Exchange/stackstorm-napalm/blob/master/actions/get_config.yaml#L23-L27

**Comment by mmihir82** [comment]
Thanks nmaludy, how about the list of devices. Do I have to mentions all devices hostname? Can it use whats available via /etc/hosts

**Comment by mmihir82** [comment]
Also Is there any way to encrypt the password file similar to ansible-vault?

**Comment by LindsayHill** [comment]
Use the datastore for encrypted credentials https://docs.stackstorm.com/datastore.html#securing-secrets-admin-only

**Comment by mmihir82** [comment]
@LindsayHill thanks for the link
